set -g @powerkit_theme "tokyo-night"
set -g @powerkit_theme_variant "night"

# Plugins
set -g @powerkit_plugins "git,hostname"

# Separator style (normal, rounded, flame, pixel, honeycomb, none)
set -g @powerkit_separator_style "rounded"
set -g @powerkit_edge_separator_style "normal"

set -g @powerkit_transparent "true"
